import { OfficeDocument, FinanceInvoice, RegionalActivity, SetupMilestone, AppSettings, LandingPageConfig, GalleryImage } from './types';

export const initialSettings: AppSettings = {
  adminPin: 'sarajevo2026libyawics',
  directorNameAr: 'مصطفى محمود البكشي',
  directorNameBs: 'Mustafa Mahmoud Al-Bakshi',
  directorTitleAr: 'المفوض الرسمي ومدير فرع البوسنة والهرسك',
  directorTitleBs: 'Ovlašteni predstavnik i direktor ureda za BiH',
  sarajevoOfficeAddressAr: 'سراييفو، البوسنة والهرسك - شارع فرهادية، سنتر',
  sarajevoOfficeAddressBs: 'Ferhadija bb, Centar, 71000 Sarajevo, Bosna i Hercegovina',
  contactEmail: 'albkshi@gmail.com',
  contactPhone: '+387 33 000 000',
  hqEmail: 'info@wicsociety.ly',
  currencyDefault: 'BAM',
  logoSizePx: 52,
  logoFrameStyle: 'transparent',
};

export const initialLandingConfig: LandingPageConfig = {
  topBadgeAr: 'البوسنة والهرسك • منطقة البلقان وجنوب شرق أوروبا',
  topBadgeBs: 'Bosna i Hercegovina • Balkan i Jugoistočna Evropa',
  orgNameAr: 'جمعية الدعوة الإسلامية العالمية',
  orgNameBs: 'Svjetska organizacija za islamski poziv',
  subTitleAr: 'فرع سراييفو - البوسنة والهرسك',
  subTitleBs: 'Predstavništvo Sarajevo - Bosna i Hercegovina',
  heroDescriptionAr: 'الممثلية الرسمية لجمعية الدعوة الإسلامية العالمية في جمهورية البوسنة والهرسك، المعنية برعاية التراث الإسلامي، الحوار الحضاري، الأعمال الإنسانية، وتوثيق العلاقات الأخوية بين الشعوب الإسلامية ودول البلقان.',
  heroDescriptionBs: 'Zvanično predstavništvo Svjetske organizacije za islamski poziv u Bosni i Hercegovini, posvećeno očuvanju islamskog naslijeđa, civilizacijskom dijalogu, humanitarnom radu i jačanju bratskih veza na Balkanu.',
  heroImageUrl: '/mosques/begova.jpg',
  heroImageCaptionAr: 'جامع الغازي خسرو بك التاريخي (1531م) • قلب سراييفو النابض',
  heroImageCaptionBs: 'Gazi Husrev-begova džamija (1531) • Srce Sarajeva',
  showQuranVerse: true,
  quranVerseAr: '﴿ وَلْتَكُنْ مِنْكُمْ أُمَّةٌ يَدْعُونَ إِلَى الْخَيْرِ وَيَأْمُرُونَ بِالْمَعْرُوفِ وَيَنْهَوْنَ عَنِ الْمُنْكَرِ وَأُولَئِكَ هُمُ الْمُفْلِحُونَ ﴾',
  quranVerseBs: 'I neka među vama bude onih koji će na dobro pozivati i tražiti da se čini dobro, a od zla odvraćati – oni će šta žele postići.',
  quranCitationAr: '[سورة آل عمران: الآية 104]',
  quranCitationBs: '[Sura Ali \'Imran: Ajet 104]',
  stats: [
    {
      id: 'stat-1',
      value: '1531+',
      labelAr: 'تاريخ إسلامي عريق',
      labelBs: 'Bogato naslijeđe',
    },
    {
      id: 'stat-2',
      value: '5+',
      labelAr: 'مدن ومناطق رئيسية',
      labelBs: 'Regija djelovanja',
    },
    {
      id: 'stat-3',
      value: '100%',
      labelAr: 'شراكات رسمية',
      labelBs: 'Zvanična saradnja',
    },
  ],
  contactAddressAr: 'سراييفو، البوسنة والهرسك - شارع فرهادية، سنتر',
  contactAddressBs: 'Ferhadija bb, Centar, 71000 Sarajevo, Bosna i Hercegovina',
  contactPhone: '+387 33 000 000',
  contactEmail: 'albkshi@gmail.com',
  workingHoursWeekdays: '09:00 - 17:00 (CET)',
  workingHoursWeekendsAr: 'عطلة رسمية',
  workingHoursWeekendsBs: 'Zatvoreno',
};

export const initialMilestones: SetupMilestone[] = [
  {
    id: 'mile-1',
    stepNumber: 1,
    titleAr: 'توثيق قرار التكليف والترجمة القضائية المحلفة',
    titleBs: 'Ovjera odluke o ovlaštenju i sudski prijevod',
    authority: 'Sudski tumač i Notarski ured Sarajevo',
    status: 'completed',
    requiredDocsAr: ['قرار التكليف الأصلي رقم 1232/1.1', 'جواز السفر المعتمد', 'شهادة حسن سيرة'],
    requiredDocsBs: ['Originalna odluka br. 1232/1.1', 'Ovjerena kopija pasoša', 'Sudski prijevod na bosanski jezik'],
    notesAr: 'تم إنجاز الترجمة المحلفة لقرار التكليف لدى مترجم قضائي معتمد في كانتون سراييفو.',
    notesBs: 'Sudski tumač za arapski jezik u Kantonu Sarajevo izvršio službeni prijevod.',
  },
  {
    id: 'mile-2',
    stepNumber: 2,
    titleAr: 'طلب التسجيل في وزارة العدل لجمهورية البوسنة والهرسك',
    titleBs: 'Zahtjev za upis u registar predstavništava pri Ministarstvu pravde BiH',
    authority: 'Ministarstvo pravde Bosne i Hercegovine (Sarajevo)',
    status: 'in_progress',
    requiredDocsAr: ['النظام الأساسي للجمعية', 'قرار فتح الفرع وتسمية المفوض', 'استمارة طلب القيد الرسمية'],
    requiredDocsBs: ['Statut Svjetske organizacije', 'Odluka o otvaranju i imenovanju', 'Obrazac zahtjeva za upis'],
    notesAr: 'تم تجهيز مسودة الخطاب الرسمي المترجم وتقديمه للمراجعة لدى المستشار القانوني.',
    notesBs: 'Pripremljen službeni dopis na bosanskom jeziku za predaju u pisarnicu Ministarstva.',
  },
  {
    id: 'mile-3',
    stepNumber: 3,
    titleAr: 'استخراج الرقم الضريبي وإشعار مصلحة الضرائب',
    titleBs: 'Dobijanje JIB/PIB broja pri Poreznoj upravi Federacije BiH',
    authority: 'Porezna uprava FBiH - Kantonalni porezni ured Sarajevo',
    status: 'pending',
    requiredDocsAr: ['قرار وزارة العدل بالترخيص', 'عقد إيجار مقر المكتب', 'استمارة تسجيل المكلف الضريبي'],
    requiredDocsBs: ['Rješenje Ministarstva pravde BiH', 'Ugovor o zakupu prostora', 'Obrazac za registraciju poreznog obveznika'],
    notesAr: 'يلزم الحصول على قرار التسجيل أولاً لمباشرة الإجراء الضريبي.',
    notesBs: 'Slijedi odmah po izdavanju rješenja Ministarstva pravde.',
  },
  {
    id: 'mile-4',
    stepNumber: 4,
    titleAr: 'فتح الحساب المصرفي الرسمي للفرع في سراييفو',
    titleBs: 'Otvaranje službenog bankovnog računa u Sarajevu',
    authority: 'BBI Bank (Bosna Bank International) / Ziraat Bank Sarajevo',
    status: 'pending',
    requiredDocsAr: ['شهادة القيد والتسجيل', 'الرقم الضريبي', 'نماذج توقيع المفوض المعتمد'],
    requiredDocsBs: ['Rješenje o registraciji', 'Uvjerenje o poreznoj registraciji', 'Karton deponovanih potpisa'],
    notesAr: 'تم التنسيق المبدئي لفتح الحساب التشغيلي لتحويل مخصصات الفرع.',
    notesBs: 'Usklađeno za otvaranje transakcijskog računa u KM i deviznog računa.',
  },
  {
    id: 'mile-5',
    stepNumber: 5,
    titleAr: 'افتتاح المقر وتدشين الأنشطة الرسمية بالتنسيق مع الجهات المعنية',
    titleBs: 'Svečano otvaranje ureda i koordinacija s institucijama',
    authority: 'Grad Sarajevo, Islamska zajednica u BiH, Diplomatski kor',
    status: 'pending',
    requiredDocsAr: ['دعوات الافتتاح الرسمية', 'تقرير التدشين للإدارة العامة', 'بروتوكولات التعاون'],
    requiredDocsBs: ['Službene pozivnice', 'Plan regionalnih humanitarnih i kulturnih projekata', 'Protokoli o saradnji'],
    notesAr: 'التنسيق لإقامة حفل استقبال بحضور وفد الجمعية والجهات الرسمية.',
    notesBs: 'Planiranje inauguracije ureda u Sarajevu uz prisustvo delegacije iz Tripolija.',
  },
];

export const initialDocuments: OfficeDocument[] = [
  {
    id: 'doc-mandate-01',
    refNumber: '1232/1.1',
    titleAr: 'قرار تكليف بفتح فرع جمعية الدعوة الإسلامية العالمية في البوسنة والهرسك',
    titleBs: 'Odluka o ovlaštenju za otvaranje ureda Svjetske organizacije u BiH',
    category: 'mandate',
    recipientAr: 'السيد / مصطفى محمود البكشي المحترم',
    recipientBs: 'Poštovani g. Mustafa Mahmoud Al-Bakshi',
    recipientOrg: 'World Islamic Call Society Headquarters',
    contentAr: `في إطار تفعيل وتطوير التعاون الدعوي والثقافي والإسلامي بين جمعية الدعوة الإسلامية العالمية وجمهورية البوسنة والهرسك.
يُسعدنا إبلاغكم بأنه قد تقرر تكليفكم رسمياً بمهمة فتح وإنشاء فرع معتمد للجمعية في جمهورية البوسنة والهرسك.
وبموجب هذا التكليف، تُمكّنون من الصلاحيات والمهام التالية:
1. إتخاذ كافة الإجراءات الإدارية والقانونية والمالية اللازمة لإتمام عملية التسجيل والافتتاح وفق اللوائح والقوانين النافذة في البوسنة والهرسك.
2. الاستعانة بالمكاتب القانونية والمحامين المعتمدين والمستشارين المحليين لإتمام كافة المعاملات والتوثيقات الرسمية.
3. تمثيل الجمعية أمام الجهات الحكومية والرسمية والمؤسسات ذات الصلة داخل جمهورية البوسنة والهرسك لغرض الافتتاح.
نأمل منكم المباشرة في اتخاذ الإجراءات اللازمة موافاتنا بتقرير دوري يوضح مسار الخطوات المتبعة.
شاكرين لكم جهودكم، ومتمنين لكم التوفيق والسداد.`,
    contentBs: `U okviru aktiviranja i unapređenja vjerske, kulturne i islamske saradnje između Svjetske organizacije za islamski poziv (World Islamic Call Society) i Bosne i Hercegovine.
Sa zadovoljstvom vas obavještavamo da ste zvanično zaduženi za uspostavljanje i otvaranje ovlaštenog ureda/predstavništva Organizacije u Bosni i Hercegovini.
Na osnovu ovog ovlaštenja, povjeravaju vam se sljedeća ovlaštenja i zadaci:
1. Poduzimanje svih administrativnih, pravnih i finansijskih mjera neophodnih za završetak postupka registracije i otvaranja u skladu s važećim zakonima i propisima u Bosni i Hercegovini.
2. Angažovanje ovlaštenih advokatskih kancelarija, notara i lokalnih pravnih savjetnika za obavljanje svih službenih poslova i ovjera.
3. Zastupanje Organizacije pred svim vladinim, službenim organima i relevantnim institucijama u Bosni i Hercegovini u svrhu otvaranja predstavništva.
Očekujemo da bez odlaganja započnete neophodne procedure i dostavljate nam redovne periodične izvještaje o toku poduzetih koraka.
Zahvaljujemo na vašem trudu i želimo vam uspjeh.`,
    dateGregorian: '2026-09-03',
    dateHijri: '20 ربيع الأول 1448 هـ',
    status: 'approved',
    authorizedSignatoryAr: 'الممثل القانوني: أ.د. صالح سليم الفاخري',
    authorizedSignatoryBs: 'Pravni zastupnik: Prof. dr. Saleh Salim Al-Fakhri',
    notes: 'وثيقة التكليف الرسمية المعتمدة - أصل الورقة المؤرخة 2026/9/3',
    createdAt: '2026-09-03T10:00:00Z',
    updatedAt: '2026-09-03T10:00:00Z',
    attachmentsCount: 1,
  },
  {
    id: 'doc-gov-02',
    refNumber: 'WICS-SJJ/2026-001',
    titleAr: 'طلب تسجيل فرع منظمة أجنبية لدى وزارة العدل في البوسنة والهرسك',
    titleBs: 'Zahtjev za upis u registar predstavništva strane nevladine organizacije',
    category: 'ministry_application',
    recipientAr: 'معالي وزير العدل في البوسنة والهرسك المحترم - سراييفو',
    recipientBs: 'Ministarstvo pravde Bosne i Hercegovine, Odjel za upravu, Trg BiH 1, Sarajevo',
    recipientOrg: 'Ministarstvo pravde BiH',
    contentAr: `معالي وزير العدل الموقر،
تحية طيبة وبعد،،
نتشرف نحن، فرع جمعية الدعوة الإسلامية العالمية، بأن نتقدم إلى معاليكم بطلبنا الرسمي هذا للقيد والتسجيل في سجل فروع وممثليات المنظمات الأجنبية غير الحكومية في البوسنة والهرسك، استناداً إلى قانون الجمعيات والمؤسسات النافذ في جمهورية البوسنة والهرسك.
نرفق لمعاليكم طيه كافة المسوغات القانونية المعتمدة:
1. قرار التكليف وتسمية الممثل القانوني المفوض (السيد/ مصطفى محمود البكشي) مترجماً ترجمة قضائية ومصدقاً أصولاً.
2. النظام الأساسي المعتمد للجمعية الأم وعقد التأسيس.
3. إثبات الشخصية للممثل المعتمد وعنوان المقر المختار في سراييفو.
نرجو من معاليكم التكرم بإصدار القرار اللازم بالقيد في السجل الرسمي للمنظمات، وتمكيننا من ممارسة مهامنا الثقافية والإنسانية الرامية لتعزيز أواصر الصداقة والتعاون.
وتفضلوا بقبول فائق التقدير والاحترام.`,
    contentBs: `Poštovani ministre,
Obraćamo vam se u ime Svjetske organizacije za islamski poziv (World Islamic Call Society) sa službenim zahtjevom za upis našeg predstavništva u Registar predstavništava stranih nevladinih organizacija u Bosni i Hercegovini, u skladu sa Zakonom o udruženjima i fondacijama Bosne i Hercegovine.
Uz ovaj zahtjev prilažemo svu propisanu pravnu dokumentaciju:
1. Odluku o otvaranju predstavništva i imenovanju ovlaštenog lica (g. Mustafa Mahmoud Al-Bakshi), prevedenu od strane stalnog sudskog tumača i uredno ovjerenu.
2. Statut matične organizacije i dokaz o registraciji u zemlji porijekla.
3. Identifikacioni dokument ovlaštenog predstavnika i dokaz o obezbijeđenom sjedištu ureda u Sarajevu.
Ljubazno molimo Ministarstvo da donese rješenje o upisu u službeni registar, kako bismo mogli legalno realizirati humanitarne, kulturne i edukativne programe u Bosni i Hercegovini.
S osobitim poštovanjem.`,
    dateGregorian: '2026-09-06',
    dateHijri: '23 ربيع الأول 1448 هـ',
    status: 'submitted',
    authorizedSignatoryAr: 'مصطفى محمود البكشي - مدير الفرع',
    authorizedSignatoryBs: 'Mustafa Mahmoud Al-Bakshi - Direktor ureda',
    notes: 'تم إعداد الطلب الرسمي وتقديمه إلى قلم وزارة العدل في سراييفو.',
    createdAt: '2026-09-06T09:30:00Z',
    updatedAt: '2026-09-06T09:30:00Z',
    attachmentsCount: 3,
  },
  {
    id: 'doc-gov-03',
    refNumber: 'WICS-SJJ/2026-002',
    titleAr: 'كتاب موجه لمصلحة الضرائب لطلب فتح الملف الضريبي واستخراج الرقم التعريفي',
    titleBs: 'Dopis Kantonalnom poreznom uredu Sarajevo za izdavanje identifikacionog broja',
    category: 'government_letter',
    recipientAr: 'إدارة مصلحة الضرائب الفيدرالية - مكتب كانتون سراييفو المحترمين',
    recipientBs: 'Porezna uprava FBiH - Kantonalni porezni ured Sarajevo',
    recipientOrg: 'Porezna uprava FBiH',
    contentAr: `السادة إدارة الضرائب في كانتون سراييفو،
تحية طيبة وبعد،،
بصفتنا الممثل المعتمد لفرع جمعية الدعوة الإسلامية العالمية في البوسنة والهرسك، نتقدم إليكم بطلبنا الرسمي لفتح ملف ضريبي واستخراج الرقم التعريفي الضريبي (JIB) للفرع، وذلك لتمكيننا من تسوية الالتزامات المالية والضريبية وفق اللوائح السارية في اتحاد البوسنة والهرسك.
مرفق طيه صورة قرار التكليف وعقد الإيجار للمقر الكائن في سراييفو، ووثائق الهوية الرسمية.
شاكرين حسن تعاونكم المسبق.`,
    contentBs: `Poštovani,
U svojstvu ovlaštenog predstavnika ureda Svjetske organizacije za islamski poziv u Bosni i Hercegovini, podnosimo zahtjev za otvaranje poreznog dosjea i dodjelu jedinstvenog identifikacionog broja (JIB) za naš ured, u svrhu zakonitog izmirivanja svih fiskalnih obaveza u Federaciji Bosne i Hercegovine.
U prilogu dostavljamo odluku o imenovanju, ugovor o zakupu poslovnog prostora u Sarajevu i ličnu dokumentaciju.
Zahvaljujemo na saradnji.`,
    dateGregorian: '2026-09-07',
    dateHijri: '24 ربيع الأول 1448 هـ',
    status: 'draft',
    authorizedSignatoryAr: 'مصطفى محمود البكشي',
    authorizedSignatoryBs: 'Mustafa Mahmoud Al-Bakshi',
    notes: 'جاهز للإرسال فور استلام إشعار وزارة العدل.',
    createdAt: '2026-09-07T14:15:00Z',
    updatedAt: '2026-09-07T14:15:00Z',
    attachmentsCount: 2,
  },
];

export const initialInvoices: FinanceInvoice[] = [
  {
    id: 'inv-001',
    invoiceNumber: 'ADV-SJJ-2026/01',
    type: 'expense',
    date: '2026-09-04',
    dueDate: '2026-09-15',
    vendorNameAr: 'مكتب المحاماة والاستشارات القانونية - سراييفو',
    vendorNameBs: 'Advokatska kancelarija & Pravno savjetovanje Sarajevo',
    vendorTaxId: '4201889920001',
    category: 'legal_counsel',
    currency: 'BAM',
    items: [
      {
        id: 'item-1',
        descriptionAr: 'دراسة ومراجعة اللوائح وقوانين تسجيل المنظمات الأجنبية في البوسنة',
        descriptionBs: 'Pravna analiza i usklađivanje akata za registraciju stranog udruženja',
        quantity: 1,
        unitPrice: 800.0,
        total: 800.0,
      },
      {
        id: 'item-2',
        descriptionAr: 'صياغة الطلب ومتابعة الإجراءات لدى وزارة العدل في البوسنة والهرسك',
        descriptionBs: 'Sastavljanje zahtjeva i zastupanje pred Ministarstvom pravde BiH',
        quantity: 1,
        unitPrice: 1200.0,
        total: 1200.0,
      },
    ],
    subtotal: 2000.0,
    vatRate: 17,
    vatAmount: 340.0,
    totalAmount: 2340.0,
    paymentStatus: 'paid',
    paymentMethod: 'bank_transfer',
    notesAr: 'تم سداد الدفعة بموجب إشعار تحويل مصرفي رسمي للمحامي المعتمد.',
    notesBs: 'Uredno plaćeno putem bankovnog naloga ovlaštenom advokatu.',
    approvedByDirector: true,
    createdAt: '2026-09-04T11:00:00Z',
  },
  {
    id: 'inv-002',
    invoiceNumber: 'TRN-SJJ-2026/08',
    type: 'expense',
    date: '2026-09-05',
    dueDate: '2026-09-10',
    vendorNameAr: 'المترجم القضائي المحلف للغة العربية - سراييفو',
    vendorNameBs: 'Stalni sudski tumač za arapski jezik Sarajevo',
    vendorTaxId: '4300998810003',
    category: 'translation_sworn',
    currency: 'BAM',
    items: [
      {
        id: 'item-3',
        descriptionAr: 'ترجمة قرار التكليف رقم 1232/1.1 وتوثيقه بالختم القضائي',
        descriptionBs: 'Službeni prijevod i ovjera odluke br. 1232/1.1 sa pečatom tumača',
        quantity: 3,
        unitPrice: 35.0,
        total: 105.0,
      },
      {
        id: 'item-4',
        descriptionAr: 'ترجمة النظام الأساسي وشهادات التسجيل الرسمية من العربية إلى البوسنية',
        descriptionBs: 'Prijevod statuta i popratnih certifikata s arapskog na bosanski jezik',
        quantity: 12,
        unitPrice: 30.0,
        total: 360.0,
      },
    ],
    subtotal: 465.0,
    vatRate: 0,
    vatAmount: 0.0,
    totalAmount: 465.0,
    paymentStatus: 'paid',
    paymentMethod: 'cash',
    notesAr: 'ترجمة معتمدة صالحة للتقديم الرسمي لكافة الدوائر الحكومية في البوسنة.',
    notesBs: 'Prijevodi prihvaćeni i ovjereni za upotrebu pred državnim organima.',
    approvedByDirector: true,
    createdAt: '2026-09-05T15:20:00Z',
  },
  {
    id: 'inv-003',
    invoiceNumber: 'RENT-SJJ-2026/09',
    type: 'expense',
    date: '2026-09-07',
    dueDate: '2026-09-20',
    vendorNameAr: 'شركة تأجير العقارات والمكاتب - شارع فرهادية سراييفو',
    vendorNameBs: 'Nekretnine & Poslovni prostori Centar Sarajevo d.o.o.',
    vendorTaxId: '4200776650009',
    category: 'office_rent_deposit',
    currency: 'EUR',
    items: [
      {
        id: 'item-5',
        descriptionAr: 'إيجار مقر مكتب الجمعية في سنتر سراييفو لشهر سبتمبر 2026',
        descriptionBs: 'Mjesečni zakup ureda u centru Sarajeva za septembar 2026.',
        quantity: 1,
        unitPrice: 1200.0,
        total: 1200.0,
      },
      {
        id: 'item-6',
        descriptionAr: 'مبلغ التأمين المسترد لمقر المكتب (شهرين)',
        descriptionBs: 'Sigurnosni depozit za zakup poslovnog prostora (2 mjeseca)',
        quantity: 1,
        unitPrice: 2400.0,
        total: 2400.0,
      },
    ],
    subtotal: 3600.0,
    vatRate: 0,
    vatAmount: 0.0,
    totalAmount: 3600.0,
    paymentStatus: 'pending',
    paymentMethod: 'bank_transfer',
    notesAr: 'بانتظار اعتماد تحويل المبلغ من الحساب المصرفي المركزي.',
    notesBs: 'Na čekanju za realizaciju bankovnog transfera iz Tripolija.',
    approvedByDirector: false,
    createdAt: '2026-09-07T08:00:00Z',
  },
];

export const initialActivities: RegionalActivity[] = [
  {
    id: 'act-01',
    titleAr: 'انطلاق الترتيبات الرسمية لافتتاح مقر جمعية الدعوة الإسلامية العالمية في سراييفو',
    titleBs: 'Početak službenih priprema za otvaranje ureda WICS-a u Sarajevu',
    date: '2026-09-04',
    location: 'Sarajevo',
    category: 'diplomatic',
    summaryAr: 'باشر السيد مصطفى محمود البكشي الإجراءات الرسمية والقانونية لفتح الفرع المعتمد للجمعية في سراييفو تنفيذاً لقرار التكليف رقم 1232/1.1 الصادر عن الإدارة العامة.',
    summaryBs: 'Predstavnik Mustafa Mahmoud Al-Bakshi započeo je administrativne i pravne procedure za uspostavu zvaničnog ureda Svjetske organizacije u Sarajevu.',
    detailsAr: 'عقد وفد التأسيس عدة لقاءات مع مكاتب الاستشارات القانونية في العاصمة سراييفو، تمهيداً لإيداع ملف التسجيل لدى وزارة العدل في البوسنة والهرسك، وبحث آفاق الشراكة الثقافية والإنسانية مع المؤسسات المحلية.',
    detailsBs: 'Održani su inicijalni sastanci s pravnim savjetnicima u Sarajevu radi pripreme dokumentacije za predaju Ministarstvu pravde BiH, te otvaranje mogućnosti kulturne i obrazovne saradnje.',
    imageUrl: '/images/diplomatic-meeting.jpg',
    partnerOrganization: 'Ministarstvo pravde BiH & Notarski ured',
    published: true,
    createdAt: '2026-09-04T12:00:00Z',
  },
  {
    id: 'act-02',
    titleAr: 'تنسيق برامج المساعدات الإنسانية ودعم مراكز التعليم واللغة العربية في البوسنة',
    titleBs: 'Koordinacija humanitarnih programa i podrške centrima za arapski jezik u BiH',
    date: '2026-09-06',
    location: 'Sarajevo - Mostar - Zenica',
    category: 'humanitarian',
    summaryAr: 'إعداد خطة عمل استراتيجية للبرامج الإغاثية والتعليمية التي ستنفذها الجمعية في مختلف المدن البوسنية بالتنسيق مع الجهات الأهلية والرسمية.',
    summaryBs: 'Priprema strateškog plana humanitarnih i obrazovnih projekata koje će organizacija provoditi u gradovima širom Bosne i Hercegovine.',
    detailsAr: 'تشمل الخطة توزيع المنح الدراسية للطلبة المتميزين، ودعم دور تحفيظ القرآن الكريم ومراكز تعليم اللغة العربية، إضافة إلى مبادرات التكافل الاجتماعي للمحتاجين في موسم الشتاء القادم.',
    detailsBs: 'Plan obuhvata stipendiranje nadarenih studenata, podršku centrima za učenje jezika i kurseva, te zimske humanitarne pakete za socijalno ugrožene porodice.',
    imageUrl: '/images/humanitarian-aid.jpg',
    partnerOrganization: 'Udruženja građana i humanitarne organizacije u BiH',
    published: true,
    createdAt: '2026-09-06T16:00:00Z',
  },
  {
    id: 'act-03',
    titleAr: 'ملتقى حوار الثقافات والتسامح في منطقة البلقان - التحضيرات للمؤتمر السنوي',
    titleBs: 'Pripreme za konferenciju o međukulturnom dijalogu i suživotu na Balkanu',
    date: '2026-09-07',
    location: 'Sarajevo',
    category: 'dialogue',
    summaryAr: 'مشاورات أولية مع الأكاديميين والمفكرين في جامعات سراييفو لتنظيم ندوة دولية حول قيم الحوار الإسلامي والتعايش السلمي في منطقة البلقان.',
    summaryBs: 'Inicijalne konsultacije s akademskim krugovima u Sarajevu radi organizacije međunarodnog simpozija o miru, dijalogu i saradnji.',
    detailsAr: 'يهدف المؤتمر المزمع عقده بعد اكتمال افتتاح المقر إلى إبراز الدور الحضاري والإنساني لجمعية الدعوة الإسلامية العالمية في مد جسور التواصل والتعارف بين الشعوب.',
    detailsBs: 'Simpozij ima za cilj promoviranje univerzalnih vrijednosti tolerancije, uzajamnog poštovanja i saradnje među različitim zajednicama u regiji jugoistočne Evrope.',
    imageUrl: '/images/cultural-dialogue.jpg',
    partnerOrganization: 'Univerzitet u Sarajevu & Istraživački centri',
    published: true,
    createdAt: '2026-09-07T18:30:00Z',
  },
];

export const initialGalleryImages: GalleryImage[] = [
  {
    id: 'img-begova',
    titleAr: 'جامع الغازي خسرو بك - باشتشارشيا سراييفو',
    titleBs: 'Gazi Husrev-begova džamija - Baščaršija Sarajevo',
    category: 'mosque',
    imageUrl: '/mosques/begova.jpg',
    descriptionAr: 'درة العمارة الإسلامية في قلب سراييفو النابض، شيد عام 1531م',
    descriptionBs: 'Najznačajniji islamski sakralni objekat u BiH (1531)',
    tags: ['سراييفو', 'مسجد', 'Sarajevo', 'Džamija'],
    sizeKb: 145,
    uploadedAt: '2026-09-01T10:00:00Z',
    isBuiltIn: true,
  },
  {
    id: 'img-careva',
    titleAr: 'الجامع الإمبراطوري (جامع السلطان) - سراييفو',
    titleBs: 'Careva džamija - Sarajevo',
    category: 'mosque',
    imageUrl: '/mosques/careva.jpg',
    descriptionAr: 'أقدم مساجد سراييفو التاريخية ومقر الرياسة الإسلامية',
    descriptionBs: 'Najstarija džamija u Sarajevu, zadužbina Isa-bega Ishakovića',
    tags: ['سراييفو', 'تاريخ', 'مسجد'],
    sizeKb: 160,
    uploadedAt: '2026-09-01T10:30:00Z',
    isBuiltIn: true,
  },
  {
    id: 'img-ferhadija-sjj',
    titleAr: 'جامع الفرهادية - شارع المشاة سنتر سراييفو',
    titleBs: 'Ferhadija džamija - Centar Sarajevo',
    category: 'mosque',
    imageUrl: '/mosques/ferhadija-sarajevo.jpg',
    descriptionAr: 'تحفة الزخارف النباتية والجداريات الكلاسيكية للقرن الـ16',
    descriptionBs: 'Znamenita džamija u pješačkoj zoni Ferhadija',
    tags: ['فرهادية', 'سراييفو', 'زخارف'],
    sizeKb: 152,
    uploadedAt: '2026-09-01T11:00:00Z',
    isBuiltIn: true,
  },
  {
    id: 'img-aladza',
    titleAr: 'جامع الآلاجا الأثري الملون - فوتشا',
    titleBs: 'Aladža džamija - Foča',
    category: 'mosque',
    imageUrl: '/mosques/aladza.jpg',
    descriptionAr: 'التحفة الشرقية ذات النقوش الملونة على نهر درينا (1550م)',
    descriptionBs: 'Šarena ljepotica na obali Drine, biser osmanske arhitekture',
    tags: ['فوتشا', 'الآلاجا', 'Foča'],
    sizeKb: 175,
    uploadedAt: '2026-09-01T11:30:00Z',
    isBuiltIn: true,
  },
  {
    id: 'img-ferhadija-bl',
    titleAr: 'جامع الفرهادية التاريخي - بانيا لوكا',
    titleBs: 'Ferhadija džamija - Banja Luka',
    category: 'mosque',
    imageUrl: '/mosques/ferhadija-banjaluka.jpg',
    descriptionAr: 'معلم تاريخي وثقافي بارز أسسه فرحات باشا سوكولوفيتش (1579م)',
    descriptionBs: 'Historijsko zdanje Ferhad-paše Sokolovića u Banjoj Luci',
    tags: ['بانيا لوكا', 'Banja Luka', 'تراث'],
    sizeKb: 168,
    uploadedAt: '2026-09-01T12:00:00Z',
    isBuiltIn: true,
  },
  {
    id: 'img-karadoz-beg',
    titleAr: 'جامع قره جوز بك - موستار',
    titleBs: 'Karađoz-begova džamija - Mostar',
    category: 'mosque',
    imageUrl: '/mosques/karadoz-beg.jpg',
    descriptionAr: 'أضخم مساجد الهرسك بتصميم المعمار سنان الشهير (1557م)',
    descriptionBs: 'Najmonumentalnija džamija u Hercegovini, djelo Mimara Sinana',
    tags: ['موستار', 'Mostar', 'سنان'],
    sizeKb: 180,
    uploadedAt: '2026-09-01T12:30:00Z',
    isBuiltIn: true,
  },
  {
    id: 'img-koski-mehmed',
    titleAr: 'جامع كوسكي محمد باشا - مطل نهر نيريتفا موستار',
    titleBs: 'Koski Mehmed-pašina džamija - Mostar',
    category: 'mosque',
    imageUrl: '/mosques/koski-mehmed.jpg',
    descriptionAr: 'المسجد الشاهق المطل على الجسر القديم ونهر نيريتفا الرقراق',
    descriptionBs: 'Džamija uz kanjon Neretve s pogledom na Stari most',
    tags: ['موستار', 'نيريتفا', 'Mostar'],
    sizeKb: 190,
    uploadedAt: '2026-09-01T13:00:00Z',
    isBuiltIn: true,
  },
  {
    id: 'img-sarena-travnik',
    titleAr: 'الجامع الملون (جامع السليمانية) - ترافنيك',
    titleBs: 'Šarena (Sulejmanija) džamija - Travnik',
    category: 'mosque',
    imageUrl: '/mosques/sarena-travnik.jpg',
    descriptionAr: 'المسجد الفريد بسوقه التجاري السفلي وجدارياته البديعة (1757م)',
    descriptionBs: 'Unikatna džamija s bezistanom u prizemlju i oslikanim zidovima',
    tags: ['ترافنيك', 'Travnik', 'السليمانية'],
    sizeKb: 162,
    uploadedAt: '2026-09-01T13:30:00Z',
    isBuiltIn: true,
  },
  {
    id: 'img-act-diplomatic',
    titleAr: 'اجتماعات التأسيس الدبلوماسي والرسمي - سراييفو',
    titleBs: 'Službeni diplomatski sastanci - Sarajevo',
    category: 'activity',
    imageUrl: '/images/diplomatic-meeting.jpg',
    descriptionAr: 'التنسيق الإداري والمشاورات القانونية لافتتاح فرع الجمعية',
    descriptionBs: 'Administrativna koordinacija i pravne konsultacije za ured WICS',
    tags: ['دبلوماسي', 'افتتاح', 'سراييفو'],
    sizeKb: 135,
    uploadedAt: '2026-09-04T12:00:00Z',
    isBuiltIn: true,
  },
  {
    id: 'img-act-humanitarian',
    titleAr: 'حملات المساعدات الإنسانية والتعليمية',
    titleBs: 'Humanitarni i obrazovni programi',
    category: 'activity',
    imageUrl: '/images/humanitarian-aid.jpg',
    descriptionAr: 'برامج الدعم الإنساني للمحتاجين والمنح الدراسية',
    descriptionBs: 'Podrška porodicama i stipendije za studente',
    tags: ['إنساني', 'مساعدات', 'تعليم'],
    sizeKb: 140,
    uploadedAt: '2026-09-06T16:00:00Z',
    isBuiltIn: true,
  },
  {
    id: 'img-act-dialogue',
    titleAr: 'ملتقى حوار الثقافات والتعايش السلمي',
    titleBs: 'Međukulturni dijalog i suživot',
    category: 'activity',
    imageUrl: '/images/cultural-dialogue.jpg',
    descriptionAr: 'ندوات التواصل الحضاري والأكاديمي في جنوب شرق أوروبا',
    descriptionBs: 'Kulturni i akademski susreti za mir i saradnju',
    tags: ['حوار', 'ثقافة', 'تسامح'],
    sizeKb: 155,
    uploadedAt: '2026-09-07T18:30:00Z',
    isBuiltIn: true,
  },
  {
    id: 'img-hero-banner',
    titleAr: 'بانوراما العمارة الإسلامية والتراث البوسني',
    titleBs: 'Panorama islamskog naslijeđa u BiH',
    category: 'hero',
    imageUrl: '/images/hero-mosque.jpg',
    descriptionAr: 'بانوراما معالم البوسنة والهرسك التراثية العريقة',
    descriptionBs: 'Historijski pejzaž i arhitektura Bosne i Hercegovine',
    tags: ['واجهة', 'Hero', 'بانوراما'],
    sizeKb: 195,
    uploadedAt: '2026-09-01T08:00:00Z',
    isBuiltIn: true,
  },
];

