import { BosnianMosque } from './types';

export const historicBosnianMosques: BosnianMosque[] = [
  {
    id: 'mosque-begova',
    nameAr: 'جامع الغازي خسرو بك (بيغوفا جاميا)',
    nameBs: 'Gazi Husrev-begova džamija (Begova)',
    cityAr: 'سراييفو (باشتشارشيا)',
    cityBs: 'Sarajevo (Baščaršija)',
    yearBuilt: '1530 - 1531م (937هـ)',
    builderAr: 'الغازي خسرو بك (والي البوسنة العثماني ومؤسس نهضتها الوقفية)',
    builderBs: 'Gazi Husrev-beg (Osmanski namjesnik i veliki vakif Bosne)',
    architectAr: 'المعماري عجم أسير علي (كبير معماريي الدولة العثمانية)',
    architectBs: 'Acem Esir Ali (Glavni carski arhitekt)',
    tagAr: 'تاج العمارة الإسلامية في البلقان',
    tagBs: 'Kruna islamske arhitekture na Balkanu',
    descriptionAr: 'يعد جامع الغازي خسرو بك قلب سراييفو النابض وأعظم صرح معماري إسلامي في منطقة البلقان ككل. بُني كمركز لمجمع وقفي متكامل يضم مدرسة شرعية ومكتبة وخانقاه وحماماً وسبيل ماء وساعة قمرية (ساهات كولا). تميز الجامع بكونه أول مسجد في العالم الإسلامي تم تزويده بالكهرباء والإنارة الكهربائية في عام 1898م.',
    descriptionBs: 'Gazi Husrev-begova džamija, poznata i kao Begova džamija, najznačajniji je islamski vjerski i arhitektonski spomenik u Bosni i Hercegovini. Izgrađena u srcu Baščaršije, bila je prva džamija u svijetu koja je 1898. godine dobila električno osvjetljenje.',
    historicalSignificanceAr: 'رمز الهوية الإسلامية والتعايش الروحي في البوسنة والهرسك، ومقر إقامة الاحتفالات الدينية الرسمية لرئاسة العلماء (الرياسة).',
    historicalSignificanceBs: 'Središnji vjerski i kulturni simbol Sarajeva i Rijaseta Islamske zajednice u BiH.',
    imageUrl: '/mosques/begova.jpg',
    featuresAr: ['قبة مركزية بارتفاع 26 متراً', 'منارة أثرية بارتفاع 45 متراً', 'شاذروان حجري أصيل للتوضؤ', 'أول مسجد مضاء بالكهرباء عام 1898'],
    featuresBs: ['Glavna kupola visine 26 metara', 'Munara visine 45 metara', 'Autentični kameni šadrvan', 'Prva džamija sa strujom 1898.']
  },
  {
    id: 'mosque-careva',
    nameAr: 'الجامع الإمبراطوري (جامع السلطان / تساريفا جاميا)',
    nameBs: 'Careva džamija (Sultan-Fatihova)',
    cityAr: 'سراييفو (الضفة اليسرى لنهر ميلجاكّا)',
    cityBs: 'Sarajevo (Bistrik / Obala Miljacke)',
    yearBuilt: '1457م / جددها السلطان سليمان القانوني 1565م',
    builderAr: 'عيسى بك إسحاقوفيتش (مؤسس سراييفو) وأعاد بناءها السلطان سليمان القانوني',
    builderBs: 'Isa-beg Ishaković (Osnivač Sarajeva), obnovio Sultan Sulejman Zakonodavac',
    architectAr: 'المدرسة الكلاسيكية العثمانية',
    architectBs: 'Klasični osmanski stil gradnje',
    tagAr: 'أقدم مسجد تاريخي في سراييفو',
    tagBs: 'Najstarija historijska džamija u Sarajevu',
    descriptionAr: 'أول مسجد شُيد في سراييفو بعد الفتح، بناه مؤسس المدينة عيسى بك إسحاقوفيتش عام 1457م إهداءً للسلطان محمد الفاتح. يقع قبالة دار الرئاسة الإسلامية وعلى ضفة نهر ميلجاكّا، وتضم باحته أقدم مقبرة إسلامية لشخصيات سراييفو والعلماء ورجال الدولة.',
    descriptionBs: 'Careva džamija je najstarija džamija u Sarajevu i prva izgrađena nakon dolaska Osmanlija. Zadužbina je Isa-bega Ishakovića posvećena sultanu Mehmedu Fatihu, a današnji monumentalni oblik duguje obnovi sultana Sulejmana Veličanstvenog iz 1565. godine.',
    historicalSignificanceAr: 'المقر الشرفي للمفتي العام للبلاد وتاريخ ولادة مدينة سراييفو الحضارية.',
    historicalSignificanceBs: 'Historijsko jezgro nastanka grada Sarajeva i zdanje uz sjedište Rijaseta IZ u BiH.',
    imageUrl: '/mosques/careva.jpg',
    featuresAr: ['أقدم محراب ومنبر حجري في سراييفو', 'مئذنة مثمنة الأضلاع بديعة الزخارف', 'مقبرة تاريخية لأعيان البوسنة', 'مجلس شورى الرياسة الإسلامية مجاور'],
    featuresBs: ['Najstariji kameni mihrab u gradu', 'Osmougaona munara vrhunske obrade', 'Historijski harem sa nišanima velikana', 'Sjedište uz Rijaset IZ']
  },
  {
    id: 'mosque-ferhadija-sarajevo',
    nameAr: 'جامع الفرهادية في سراييفو',
    nameBs: 'Ferhadija džamija (Sarajevo)',
    cityAr: 'سراييفو (شارع المشاة فرهادية)',
    cityBs: 'Sarajevo (Ulica Ferhadija)',
    yearBuilt: '1561 - 1562م (969هـ)',
    builderAr: 'فرهاد بك فوكوفيتش ديسيساليتش (سنجق بك البوسنة)',
    builderBs: 'Ferhad-beg Vuković Desisalić (Bosanski sandžak-beg)',
    tagAr: 'روعة النقوش الجدارية الكلاسيكية',
    tagBs: 'Biser zidnog slikarstva iz 16. stoljeća',
    descriptionAr: 'يقع في قلب الممشى الشهير بشارع فرهادية في سراييفو. يتميز هذا المسجد بقبته الفردية الأنيقة ورواقه الثلاثي المعقود، وتعتبر النقوش الجدارية المكتشفة على جدرانه الداخلية من أندر وأجمل النماذج الزخرفية النباتية الكلاسيكية من القرن السادس عشر الميلادي.',
    descriptionBs: 'Smještena u pješačkoj zoni u samom centru grada, Ferhadija džamija predstavlja vrhunac klasične jednoprostorne potkupolne džamije. Posebno je poznata po očuvanom floralnom zidnom slikarstvu i kamenom minberu.',
    historicalSignificanceAr: 'نموذج العمارة العثمانية البوسنية الأصيلة على خط التقاء الثقافة الشرقية والغربية.',
    historicalSignificanceBs: 'Spomenik nulte kategorije na spoju osmanskog i austrougarskog dijela Sarajeva.',
    imageUrl: '/mosques/ferhadija-sarajevo.jpg',
    featuresAr: ['نقوش جدارية عثمانية أصلية', 'محراب حجري منحوت بدقة', 'موقع استراتيجي وسط سراييفو', 'شواهد قبور عثمانية أصيلة بالباحة'],
    featuresBs: ['Izvorne zidne dekoracije', 'Klesani kameni mihrab', 'Lokacija u pješačkoj zoni', 'Zeleni harem u dvorištu']
  },
  {
    id: 'mosque-karadoz-beg',
    nameAr: 'جامع قره قوز بك في موستار',
    nameBs: 'Karađoz-begova džamija (Mostar)',
    cityAr: 'موستار (الهرسك)',
    cityBs: 'Mostar (Hercegovina)',
    yearBuilt: '1557م (965هـ)',
    builderAr: 'محمد بك قره قوز (شقيق الوزير الأعظم رستم باشا)',
    builderBs: 'Mehmed-beg Karađoz (Brat velikog vezira Rustem-paše)',
    architectAr: 'المعمار سنان باشا (أشهر مهندسي العمارة الإسلامية في التاريخ)',
    architectBs: 'Mimar Sinan (Najslavniji osmanski carski graditelj)',
    tagAr: 'درة المعمار سنان في إقليم الهرسك',
    tagBs: 'Djelo čuvenog Mimara Sinana u Hercegovini',
    descriptionAr: 'أكبر وأفخم جامع تاريخي في إقليم الهرسك، صممه المعماري الإمبراطوري العبقري معمار سنان. يتمتع المسجد بقبة عالية ورواق خارجي تعلوه ثلاث قباب متناسقة ومنارة رشيقة بارتفاع 34.5 متراً مبنية من حجر التينسيتا الموستاري الشهير.',
    descriptionBs: 'Najveća i najmonumentalnija džamija u Hercegovini, izgrađena prema nacrtima carskog arhitekte Mimara Sinana. Krasi je vitka munara i trijem sa tri male kupole, a u dvorištu se nalaze šadrvan i medresa.',
    historicalSignificanceAr: 'أعلى وأرقى صرح إسلامي أثري في حوض الهرسك ومحطة هامة لرواد التاريخ والثقافة.',
    historicalSignificanceBs: 'Nacionalni spomenik BiH i remek-djelo sakralne arhitekture Hercegovine.',
    imageUrl: '/mosques/karadoz-beg.jpg',
    featuresAr: ['تصميم المعماري الشهير معمار سنان', 'مئذنة حجرية بارتفاع 34.5 متراً', 'أعمدة رخامية ذات تيجان مقرنصة', 'مدرسة شرعية ومكتبة تاريخية تابعة'],
    featuresBs: ['Projekt Mimara Sinana', 'Munara od 34,5 m', 'Mramorni stubovi sa stalaktitima', 'Karađoz-begova medresa u kompleksu']
  },
  {
    id: 'mosque-koski-mehmed',
    nameAr: 'جامع كوشكي محمد باشا في موستار',
    nameBs: 'Koski Mehmed-pašina džamija (Mostar)',
    cityAr: 'موستار (المطلة على نهر نيريتفا والجسر القديم)',
    cityBs: 'Mostar (Na litici iznad Neretve uz Stari Most)',
    yearBuilt: '1618م',
    builderAr: 'كوشكي محمد باشا (من رجال البلاط العثماني)',
    builderBs: 'Koski Mehmed-paša',
    tagAr: 'إطلالة آسرة على الجسر القديم ونيريتفا',
    tagBs: 'Najljepši pogled na Stari most i Neretvu',
    descriptionAr: 'مسجد بديع ينتصب على صخور وادي نيريتفا شديدة الانحدار، على بعد أمتار من جسر موستار القديم المدرج على لائحة التراث العالمي (اليونسكو). يشتهر المسجد بإطلالته البانورامية الخلابة على النهر الفيروزي والجسر القديم، وبزجاجه المعشق الملون الذي لا يزال محتفظاً ببريقه الأصلي.',
    descriptionBs: 'Smještena na samoj litici iznad smaragdne Neretve, svega stotinjak metara od Starog mosta, ova džamija nudi najpoznatiji vidikovac u Mostaru. Unutrašnjost čuva autentične kaligrafske natpise i obojeno staklo.',
    historicalSignificanceAr: 'أيقونة التراث البوسني التي تجسد الانسجام الأسطوري بين العمارة الإسلامية والطبيعة النهرية العذراء.',
    historicalSignificanceBs: 'Jedna od najfotografisanijih džamija na Mediteranu i Balkanu.',
    imageUrl: '/mosques/koski-mehmed.jpg',
    featuresAr: ['شرفة المئذنة تطل مباشرة على الجسر القديم', 'زجاج معشق ملون منذ القرن السابع عشر', 'حديقة مطلة على مياه نيريتفا الفيروزية', 'قبة حجرية بارتفاع 12.5 متراً'],
    featuresBs: ['Vidikovac s munare na Stari most', 'Originalno vitražno staklo', 'Avlija nad kanjonom Neretve', 'Kupola promjera 10 metara']
  },
  {
    id: 'mosque-aladza',
    nameAr: 'جامع ألاجا (المسجد الملون في فوتشا)',
    nameBs: 'Aladža džamija (Šarena džamija u Foči)',
    cityAr: 'فوتشا (شرق البوسنة على نهر درينا)',
    cityBs: 'Foča (Istočna Bosna / Uz rijeku Drinu)',
    yearBuilt: '1550م (أُعيد افتتاحها عام 2019م)',
    builderAr: 'حسن نذير (المشرف على الأملاك الإمبراطورية)',
    builderBs: 'Hasan Nezir (Carski nadzornik)',
    architectAr: 'معمار رمضان (من تلاميذ المعمار سنان)',
    architectBs: 'Mimar Ramadan (Sinanov saradnik)',
    tagAr: 'تحفة الزخارف الجدارية ووردات الحجر',
    tagBs: 'Biser osmanske sakralne ornamentike',
    descriptionAr: 'تُعرف باسم "المسجد الملون" بسبب ثراء زخارفها الجدارية المستوحاة من الطراز الإسطنبولي الباذخ. وصفها الرحالة أوليا جلبي بأنها "آية في الجمال تفوق الوصف". أُعيد بناؤها حجراً بحجر وفق تصاميمها وموادها الأصلية وافتتحت رسمياً عام 2019 بمشاركة دولية واسعة.',
    descriptionBs: 'Aladža ili Šarena džamija u Foči bila je proglašena za jedno od najsavršenijih ostvarenja osmanske arhitekture na Balkanu. Njene unutrašnje freske, kamene rozete i šadrvan predstavljaju vrhunac estetike 16. stoljeća. Potpuno je obnovljena i otvorena 2019. godine.',
    historicalSignificanceAr: 'شاهد حي على انبعاث التراث الإسلامي البوسني بعد التدمير ورسالة سلام وأمل للمستقبل.',
    historicalSignificanceBs: 'Simbol nade, ponovnog rađanja i očuvanja neprocjenjive kulturne baštine u Podrinju.',
    imageUrl: '/mosques/aladza.jpg',
    featuresAr: ['زخارف نباتية وهندسية متعددة الألوان', 'وردات حجرية منحوتة في الواجهات', 'شاذروان أثري رخامي بديع', 'أعيد إعمارها بالحجارة الأصلية ذاتها'],
    featuresBs: ['Polihromno zidno slikarstvo', 'Klesane kamene rozete na fasadi', 'Mramorni šadrvan', 'Autentična rekonstrukcija izvornim kamenom']
  },
  {
    id: 'mosque-sarena-travnik',
    nameAr: 'المسجد الملون (السليمانية في ترافنيك)',
    nameBs: 'Šarena džamija / Sulejmanija (Travnik)',
    cityAr: 'ترافنيك (عاصمة وزراء البوسنة التاريخية)',
    cityBs: 'Travnik (Historijska prijestolnica bosanskih vezira)',
    yearBuilt: '1575م / أعيد بناؤها 1815م',
    builderAr: 'سليمان باشا سكوبلياك (والي البوسنة)',
    builderBs: 'Sulejman-paša Skopljak (Bosanski valija)',
    tagAr: 'المسجد الفريد بسوق البزستان السفلي',
    tagBs: 'Jedinstvena džamija sa bezistanom u prizemlju',
    descriptionAr: 'مسجد استثنائي في هندسته؛ حيث يقع مصلى الصلاة في الطابق العلوي بينما يضم الطابق الأرضي بازاراً حجرياً مقبباً (بزستان) به دكاكين تجارية يعود ريعها للوقف. كما أن واجهاته الخارجية والداخلية مغطاة بلوحات جدارية ملونة تمثل العناقيد والزهور، ومئذنته مبنية على الجانب الأيسر خلافاً للمعتاد.',
    descriptionBs: 'Sulejmanija ili Šarena džamija u Travniku jedinstvena je po tome što se u njenom kamenom prizemlju nalazi tržni centar - bezistan sa dućanima, dok je molitveni prostor na spratu. Izuzetno je bogato oslikana cvjetnim motivima i kaligrafijom.',
    historicalSignificanceAr: 'صورة حية لمدينة ترافنيك العريقة ومركز الحياة الاجتماعية والاقتصادية في عهد وزراء البوسنة.',
    historicalSignificanceBs: 'Zaštićeni nacionalni spomenik BiH i srce vezirskog grada Travnika.',
    imageUrl: '/mosques/sarena-travnik.jpg',
    featuresAr: ['سوق وبزستان حجري أسفل قاعة الصلاة', 'نقوش جدارية خارجية وداخلية نادرة', 'مئذنة فريدة قائمة على جهة اليسار', 'خشب الجوز المنقوش للمنبر والمحراب'],
    featuresBs: ['Kameni bezistan sa radnjama u prizemlju', 'Fascinantni floralni murali izvana i unutra', 'Munara s lijeve strane objekta', 'Kvalitetna stolarija od orahovog drveta']
  },
  {
    id: 'mosque-ferhadija-banjaluka',
    nameAr: 'جامع الفرهادية في بانيا لوكا',
    nameBs: 'Ferhadija džamija (Banja Luka)',
    cityAr: 'بانيا لوكا (إقليم كرايينا)',
    cityBs: 'Banja Luka (Bosanska Krajina)',
    yearBuilt: '1579م (أُعيد افتتاحها رسمياً عام 2016م)',
    builderAr: 'فرهاد باشا سوكولوفيتش (أول بكلربك لولاية البوسنة)',
    builderBs: 'Ferhad-paša Sokolović (Prvi beglerbeg Bosanskog pašaluka)',
    tagAr: 'درة العمارة العثمانية في شمال البوسنة',
    tagBs: 'Remek-djelo klasike u Bosanskoj Krajini',
    descriptionAr: 'صرح معماري مهيب أسسه فرهاد باشا سوكولوفيتش عام 1579م من أموال فدية عسكرية. تميزت بمئذنة سامقة بارتفاع 43 متراً وثلاث قباب رواقية، وشكلت مع ضريح فرهاد باشا وبرج الساعة التاريخي مجمعاً بيانياً رائعاً. أُعيد بناؤها وإعمارها بكل عناية وافتتحت رسمياً في 7 مايو 2016.',
    descriptionBs: 'Zadužbina prvog bosanskog beglerbega Ferhad-paše Sokolovića. Smatra se vrhunskim dostignućem klasične arhitekture u Bosanskoj Krajini. Ponovo je izgrađena originalnim tehnikama klesanja i svečano otvorena 2016. godine.',
    historicalSignificanceAr: 'تخليد اليوم الوطني للمساجد في البوسنة والهرسك (7 مايو) المستلهم من ذكرى هذا المسجد.',
    historicalSignificanceBs: 'U spomen na Ferhadiju, 7. maj se u Bosni i Hercegovini obilježava kao Dan džamija.',
    imageUrl: '/mosques/ferhadija-banjaluka.jpg',
    featuresAr: ['مئذنة بطول 43 متراً متناسقة النسب', 'ضريح تاريخي لفرهاد باشا سوكولوفيتش', 'أعمدة حجرية بازلتية مستخرجة محلياً', 'رمز اليوم الوطني للمساجد في البوسنة'],
    featuresBs: ['Munara visine 43 metra', 'Turbe Ferhad-paše Sokolovića', 'Autohtoni sedreni kamen', 'Dan džamija u BiH (7. maj)']
  }
];
